backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  repo: "ColliderBang/netlify-cms"
  api_root: "https://api.github.com"

media_folder: ""
publish_mode: editorial_workflow

collections:
  - name: "Post" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "/content/posts/" # The path to the folder where the documents are stored
    path: '{{slug}}/index'
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "about-the-project"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Preview", name: "preview", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Slug", name: "slug", widget: "string"}
#      - images
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "City", name: "airport-code", widget: "select", options:
          {
              - label: "Paris", value: "CDG"
              - label: "Tokyo", value: "HND"
            }
      }
